messagesucesshome: 'teleportowanie do domu'
messagesucesssethome: 'Zostales przeteleportowany'
sethomenoargs: 'Poprawne uzycie /sethome <nazwa domu>'
sethomenull: 'Dom nie istnieje'
homelist: 'Lista domow: '
homelistnull: 'Nie masz zadnych domow'
delhomenoargs: 'Poprawne uzycie /delhome <nazwa domu>'
youdeletedhome: 'Usunales dom: '
unknownhome: 'Nie masz zapisanego domu : '