
messagesucesshome: 'Teleported to:'
messagesucesssethome: 'Home set'
sethomenoargs: 'Usage /sethome <home>'
sethomenull: 'This home doesnt exist'
homelistnull: 'You dont have any home!'
homelist: 'List of homes: '
unknownhome: 'You dont have home '
delhomenoargs: 'Usage /delhome <home>'
youdeletedhome: 'Deleted home: '
item: DIAMOND
itemamount: 10
itemconsumed: 'You have increased limit!'
maxhomes: 5
youneeditem: 'If you want more homes, you have to get: '
sethome: ' - Setting home'
home: ' - Displaying list of homes'
delhome: ' - Deleting home'
youwillbetp: 'You will be teleported in: '
tpcanceled: 'You moved, so teleport is canceled'
delaytime: 3
reloadsuccesful: 'Config reloaded.'
nopermissions: 'you dont have permissions'

