messagesucesshome: 'Zostałeś przeteleportowany do'
messagesucesssethome: 'Dom ustawiony'
sethomenoargs: 'Poprawne uzycie /sethome <nazwa domu>'
sethomenull: 'Taki dom nie istnieje'
homelistnull: 'Nie masz zadnych domow!'
homelist: 'Lista domow'
unknownhome: 'Nie masz zapisanego domu'
delhomenoargs: 'Poprawne uzycie /delhome <nazwa domu>'
youdeletedhome: 'Usuniety dom: '
