messagesucesshome: 'Zostałeś przeteleportowany do '
messagesucesssethome: 'Dom ustawiony'
sethomenoargs: 'Poprawne uzycie /sethome <nazwa domu>'
sethomenull: 'Taki dom nie istnieje'
homelistnull: 'Nie masz zadnych domow!'
homelist: 'Lista domow'
unknownhome: 'Nie masz zapisanego domu '
delhomenoargs: 'Poprawne uzycie /delhome <nazwa domu>'
youdeletedhome: 'Usuniety dom: '
item: 'DIAMOND'
itemamount: 64
itemconsumed: 'Zwiekszyles limit home o 1!'
maxhomes: 5
youneeditem: 'Aby zwiększyć liczbę home zdobądź '
sethome: ' - Ustawianie domu'
home: ' - Wyswietlanie listy domow'
delhome: ' - Usuwanie domu'

