name: Multihomes
version: 1.1
main: koral.multihomes.Multihomes
api-version: 1.13
authors: [koral]
commands:
  sethome:
  home:
  delhome:
  homehelp:
  homereload:
    usage: /homereload
    description: reload configuration files
    permission: multihomes.reload
    permission-message: Sorry! You don't have permission to execute that command.
permissions:
  multihomes.reload:
    description: allows usage /homereload
    default: op

